// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emjlxgaaphxgiedezmik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtamx4Z2FhcGh4Z2llZGV6bWlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNjcyMTYsImV4cCI6MjA2MjY0MzIxNn0.ITJ6Qbk5UYGokE0gGhR4MBR-iJZGyca-OZy_y3OS5x0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);